// Client/UNO/src/Views/Game.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Card from '../components/Card.vue'
import { usePlayerStore } from '../stores/player_store'
import { game as fetchGame, onActive, draw as apiDraw, my_hand, playCardByIndex, skipTurn } from '../model/api'
import type { Card as UnoCard } from '../../../../Domain/src/model/UnoCard'
import type { IndexedUno } from '../model/game'

const route = useRoute()
const router = useRouter()
const user = usePlayerStore()

const gameId = String(route.params.id)
const active = ref<IndexedUno | undefined>(undefined)
const loading = ref(true)
const error = ref<string | null>(null)

onMounted(async () => {
  // If the browser doesn't know which player this is, redirect to the lobby
  // so the user can enter their name before entering a game URL directly.
  if (!user.player) {
    router.push('/');
    loading.value = false;
    return;
  }
  try {
    active.value = await fetchGame(gameId)
    if (active.value) await loadHand()
    await onActive((g) => {
      if (String(g.id) === gameId) {
        active.value = g
        loadHand()
      }
    })
  } catch (e: any) {
    error.value = e?.message ?? 'Failed to load game'
  } finally {
    loading.value = false
  }
})

const players = computed(() => active.value?.players ?? [])
const round = computed(() => active.value?.currentRound)
const currentPlayer = computed(() => {
  const idx = round.value?.currentPlayerIndex ?? 0
  return players.value[idx]
})
const discardTop = computed(() => round.value?.discardTop)
const isYourTurn = computed(() => {
  const me = user.player
  return !!(me && currentPlayer.value && currentPlayer.value.name === me)
})

const myScore = computed(() => {
  const me = user.player
  if (!me) return 0
  const p = players.value.find((pp: any) => pp.name === me)
  return p?.score ?? 0
})

// Winner modal state (derived from active match)
const isFinished = computed(() => !!active.value?.finished)
const winnerName = computed(() => active.value?.winner?.name ?? '')
function goToLobby() { router.push('/') }

// Local fallback for the discard top so the acting player sees the card immediately
const lastDiscard = ref<UnoCard | null>(null)
const cardToShow = computed<UnoCard | null>(() => discardTop.value ?? lastDiscard.value)

const err = ref('')
function clearErrSoon() { if (err.value) setTimeout(() => (err.value = ''), 1500) }

// Wild card color picker state
const showColorPicker = ref(false)
const pendingWildIndex = ref<number | null>(null)

// Draw modal state
const showDrawModal = ref(false)
const drawnCard = ref<UnoCard | null>(null)
const drawnIndex = ref<number | null>(null)
const drawnPlayable = ref<boolean>(false)

function openColorPickerFor(index: number) {
  pendingWildIndex.value = index
  showColorPicker.value = true
}

async function chooseColor(color: string) {
  if (pendingWildIndex.value === null) return
  const idx = pendingWildIndex.value
  // snapshot the card being played for local fallback after success
  const played = hand.value[idx] ?? null
  try {
    active.value = await playCardByIndex(String(active.value?.id), user.player!, idx, color)
    await loadHand()
    // If server already returned a discardTop we use that; otherwise show a local fallback
    if (active.value?.currentRound?.discardTop) {
      lastDiscard.value = null
    } else if (played) {
      lastDiscard.value = played as UnoCard
    }
  } catch (e: any) {
    err.value = e?.message ?? 'Illegal move'
    clearErrSoon()
  } finally {
    showColorPicker.value = false
    pendingWildIndex.value = null
  }
}

function cancelColorPick() {
  showColorPicker.value = false
  pendingWildIndex.value = null
}

async function onDraw() {
  if (!active.value || !user.player || !isYourTurn.value) return
  // close any wild picker
  showColorPicker.value = false
  pendingWildIndex.value = null
  try {
    const before = hand.value.slice()
    // perform draw on server
    active.value = await apiDraw(String(active.value.id), user.player)
    // fetch updated hand
    const updated = await my_hand(String(active.value.id), user.player)
    // compute which card was drawn (multiset diff)
    const keyFor = (c: any) => `${c.type}::${c.color ?? ''}::${c.value ?? ''}`
    const counts: Record<string, number> = {}
    for (const c of before) counts[keyFor(c)] = (counts[keyFor(c)] || 0) + 1
    let drawn: any = null
    let drawnIdx: number | null = null
    for (let i = 0; i < updated.length; i++) {
      const c = updated[i]
      const k = keyFor(c)
      if ((counts[k] || 0) > 0) {
        counts[k] = counts[k] - 1
        continue
      }
      drawn = c
      drawnIdx = i
      break
    }
    // fallback: if lengths grew and diff didn't detect, assume last card
    if (!drawn || drawnIdx === null) {
      if (updated.length > before.length) {
        drawn = updated[updated.length - 1]
        drawnIdx = updated.length - 1
      }
    }
  // update local hand to latest
  hand.value = updated
  // ensure we have a fresh top-of-discard from server after draw
  const fresh = await fetchGame(String(active.value.id))
  if (fresh) active.value = fresh
  // clear any local fallback so we always show the authoritative top card after draw
  lastDiscard.value = null
    // if a new card exists, open the draw modal; Play button enabled only if playable
    if (drawn && drawnIdx !== null) {
      const top = cardToShow.value
      const isPlayableCard = (pc: any, topc: any) => {
        if (!topc) return true
        if (pc.type === 'WILD' || pc.type === 'WILD DRAW') return true
        if (pc.type === 'NUMBERED' && topc.type === 'NUMBERED') {
          return pc.color === topc.color || pc.value === topc.value
        }
        if (pc.type === topc.type) return true
        if (pc.color && topc.color && pc.color === topc.color) return true
        return false
      }
      drawnCard.value = drawn
      drawnIndex.value = drawnIdx
      drawnPlayable.value = isPlayableCard(drawn, top)
      showDrawModal.value = true
    }
  } catch (e: any) {
    err.value = e?.message ?? 'Cannot draw now'
    clearErrSoon()
  }
}

// Play the drawn card (from the draw modal)
async function playDrawnCard() {
  if (!active.value || !user.player || drawnIndex.value === null) return
  const idx = drawnIndex.value
  const card = drawnCard.value
  if (!card) return

  // if wild, open color picker which will call play with chosenColor
  if (card.type === 'WILD' || card.type === 'WILD DRAW') {
    // reuse pendingWildIndex for the drawn index
    pendingWildIndex.value = idx
    showColorPicker.value = true
    showDrawModal.value = false
    return
  }

  try {
    active.value = await playCardByIndex(String(active.value.id), user.player, idx)
    await loadHand()
    if (active.value?.currentRound?.discardTop) {
      lastDiscard.value = null
    } else {
      lastDiscard.value = card
    }
  } catch (e: any) {
    err.value = e?.message ?? 'Illegal move'
    clearErrSoon()
  } finally {
    showDrawModal.value = false
    drawnCard.value = null
    drawnIndex.value = null
    drawnPlayable.value = false
  }
}

// Skip after drawing (ends your turn)
async function skipDrawnCard() {
  if (!active.value || !user.player) return
  try {
    await skipTurn(String(active.value.id), user.player)
  } catch (e: any) {
    err.value = e?.message ?? 'Cannot skip now'
    clearErrSoon()
  } finally {
    showDrawModal.value = false
    drawnCard.value = null
    drawnIndex.value = null
    drawnPlayable.value = false
  }
}

// Load and show the local player's hand
const hand = ref<UnoCard[]>([])
async function loadHand() {
  if (!active.value || !user.player) return
  hand.value = await my_hand(String(active.value.id), user.player)
}

// Initial hand load and refresh on active updates
onMounted(async () => {
  // after initial fetchGame completes, load hand
  const stop = watch(
    () => active.value,
    async (v) => { if (v) await loadHand() },
    { immediate: false }
  )
})

// Play a card by hand index (server expects index)
async function onPlay(idx: number) {
  if (!active.value || !user.player || !isYourTurn.value) return
  const card = hand.value[idx]
  // If the played card is a wild, open the color picker instead of sending immediately
  if (card && (card.type === 'WILD' || card.type === 'WILD DRAW')) {
    openColorPickerFor(idx)
    return
  }

  try {
    active.value = await playCardByIndex(String(active.value.id), user.player, idx)
    await loadHand()
    // if server returned a discardTop, clear local fallback
    if (active.value?.currentRound?.discardTop) {
      lastDiscard.value = null
    } else {
      lastDiscard.value = card
    }
  } catch (e: any) {
    err.value = e?.message ?? 'Illegal move'
    clearErrSoon()
  }
}
</script>

<template>
  <div class="game">
    <h2>UNO Match #{{ gameId }}</h2>

    <div v-if="loading">Loading game...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <div v-else-if="!active">Game not found.</div>

    <template v-else>
      <section class="players">
        <h3>Players</h3>
        <ul>
          <li
            v-for="p in players"
            :key="p.id"
            :class="{ current: currentPlayer && p.id === currentPlayer.id, you: user.player && p.name === user.player }"
          >
            <span>{{ p.name }}</span>
            <small>
              (cards: {{ p.handCount }} · score: {{ p.score }})
              <span v-if="currentPlayer && p.id === currentPlayer.id"> · current turn</span>
              <span v-if="user.player && p.name === user.player"> · you</span>
            </small>
          </li>
        </ul>
      </section>

      <section class="table">
        <h3>Discard pile</h3>
        <div class="discard">
          <Card v-if="cardToShow" :card="cardToShow!" />
          <div v-else class="placeholder">No discard yet</div>
        </div>
        <p class="meta">Draw pile: {{ round?.drawPileCount ?? 0 }} · Direction: {{ round?.direction === -1 ? '⟲ CCW' : '⟳ CW' }}</p>
      </section>

      <section class="actions">
        <button @click="onDraw" :disabled="!isYourTurn">Draw</button>
        <p class="hint" v-if="!isYourTurn">Wait for your turn to draw.</p>
        <p class="error" v-if="err">{{ err }}</p>
      </section>

      <section class="hand" v-if="user.player">
        <h3>{{ user.player }}'s hand (score: {{ myScore }})</h3>
        <div class="cards">
          <Card
            v-for="(c, idx) in hand"
            :key="idx + '-' + (c.color || 'WILD') + '-' + c.type + '-' + c.value"
            :card="c"
            :class="{ disabled: !isYourTurn }"
            :clickable="isYourTurn"
            @click="onPlay(idx)"
          />
        </div>
      </section>

      <!-- Wild color picker modal -->
      <div v-if="showColorPicker" class="modal-overlay">
        <div class="modal">
          <h4>Pick a color</h4>
          <div class="colors">
            <button class="color red" @click="chooseColor('RED')">Red</button>
            <button class="color blue" @click="chooseColor('BLUE')">Blue</button>
            <button class="color green" @click="chooseColor('GREEN')">Green</button>
            <button class="color yellow" @click="chooseColor('YELLOW')">Yellow</button>
          </div>
          <div class="modal-actions">
            <button @click="cancelColorPick">Cancel</button>
          </div>
        </div>
      </div>

      <!-- Draw result modal -->
      <div v-if="showDrawModal" class="modal-overlay">
        <div class="modal">
          <h4>Drawn card</h4>
          <div class="drawn-card">
            <Card v-if="drawnCard" :card="drawnCard!" />
          </div>
          <p>Would you like to play this card or skip your turn?</p>
          <div class="modal-actions">
            <button @click="playDrawnCard" :disabled="!drawnPlayable">Play</button>
            <button @click="skipDrawnCard">Skip</button>
          </div>
        </div>
      </div>

      <!-- Winner modal -->
      <div v-if="isFinished" class="modal-overlay">
        <div class="modal">
          <h3>Game Over</h3>
          <p v-if="winnerName">{{ winnerName }} reached 500 points and wins!</p>
          <p v-else>We have a winner!</p>
          <div class="modal-actions">
            <button @click="goToLobby">Return to Lobby</button>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.game {
  max-width: 960px;
  margin: 1.5rem auto;
  padding: 0 1rem;
}
.players ul {
  display: flex;
  gap: 1rem;
  list-style: none;
  padding: 0;
}
.players li {
  padding: 0.25rem 0.5rem;
  border-radius: 6px;
  background: #f5f5f5;
}
.players li.current { background: #e6f4ff; }
.players li.you { outline: 2px solid #888; }

.table { margin: 1rem 0; }
.discard { min-height: 130px; display: flex; align-items: center; }
.placeholder { padding: 0.5rem 0.75rem; color: #777; }

.meta { color: #555; margin-top: 0.25rem; }
.actions { margin-top: 0.75rem; }
.hint { color: #777; margin-top: 0.25rem; }
.error { color: #b10000; margin-top: 0.25rem; }

/* Hand layout */
.hand .cards {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem;
}
.hand .cards .card {
  flex: 0 0 auto;
}

/* Modal styles */
.modal-overlay {
  position: fixed;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 2000;
}
.modal {
  background: white;
  padding: 1rem 1.25rem;
  border-radius: 8px;
  min-width: 260px;
  text-align: center;
}
.colors { display:flex; gap:0.5rem; justify-content:center; margin:1rem 0 }
.color { padding:0.5rem 0.75rem; border-radius:6px; color:white; border:none; cursor:pointer }
.color.red { background:#e53935 }
.color.blue { background:#1e88e5 }
.color.green { background:#43a047 }
.color.yellow { background:#fbc02d; color:#222 }
.modal-actions { margin-top:0.5rem }
</style>

// Client/UNO/src/pages/Game.tsx
import React, { useEffect, useState, useMemo } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {Card} from '../components/Card'
import { useAppSelector } from '../store/hooks'
import {
  game as fetchGame,
  onActive,
  draw as apiDraw,
  my_hand,
  playCardByIndex,
  skipTurn,
} from '../services/api'
import type { Card as UnoCard } from 'Domain/src/model/UnoCard'
import type { IndexedUno } from '../services/game'
import './../styles/Game.css'

const Game: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const user = useAppSelector((state) => state.player.player)

  const [active, setActive] = useState<IndexedUno | undefined>()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [hand, setHand] = useState<UnoCard[]>([])
  const [err, setErr] = useState('')
  const [lastDiscard, setLastDiscard] = useState<UnoCard | null>(null)

  const [showColorPicker, setShowColorPicker] = useState(false)
  const [pendingWildIndex, setPendingWildIndex] = useState<number | null>(null)

  const [showDrawModal, setShowDrawModal] = useState(false)
  const [drawnCard, setDrawnCard] = useState<UnoCard | null>(null)
  const [drawnIndex, setDrawnIndex] = useState<number | null>(null)
  const [drawnPlayable, setDrawnPlayable] = useState(false)

  // Fetch game and subscribe to updates
  useEffect(() => {
    if (!user) {
      navigate('/')
      setLoading(false)
      return
    }

    const load = async () => {
      try {
        const g = await fetchGame(String(id))
        setActive(g)
        if (g) await loadHand(g)
        await onActive(async (update) => {
          if (String(update.id) === id) {
            setActive(update)
            await loadHand(update)
          }
        })
      } catch (e: any) {
        setError(e?.message ?? 'Failed to load game')
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [id, user, navigate])

  const loadHand = async (g: IndexedUno) => {
    if (!user) return
    const h = await my_hand(String(g.id), user)
    setHand(h)
  }

  const players = active?.players ?? []
  const round = active?.currentRound
  const currentPlayer = players[round?.currentPlayerIndex ?? 0]
  const discardTop = round?.discardTop
  const isYourTurn = user && currentPlayer?.name === user

  const myScore = useMemo(() => {
    const me = players.find((p) => p.name === user)
    return me?.score ?? 0
  }, [players, user])

  const isFinished = !!active?.finished
  const winnerName = active?.winner?.name ?? ''

  const cardToShow = discardTop ?? lastDiscard

  const clearErrSoon = () => setTimeout(() => setErr(''), 1500)

  const openColorPickerFor = (index: number) => {
    setPendingWildIndex(index)
    setShowColorPicker(true)
  }

  const chooseColor = async (color: string) => {
    if (pendingWildIndex == null || !active || !user) return
    const idx = pendingWildIndex
    const played = hand[idx]
    try {
      const updated = await playCardByIndex(String(active.id), user, idx, color)
      setActive(updated)
      await loadHand(updated)
      setLastDiscard(updated.currentRound?.discardTop ? null : played)
    } catch (e: any) {
      setErr(e?.message ?? 'Illegal move')
      clearErrSoon()
    } finally {
      setShowColorPicker(false)
      setPendingWildIndex(null)
    }
  }

  const onPlay = async (idx: number) => {
    if (!active || !user || !isYourTurn) return
    const card = hand[idx]
    if (card.type === 'WILD' || card.type === 'WILD DRAW') {
      openColorPickerFor(idx)
      return
    }
    try {
      const updated = await playCardByIndex(String(active.id), user, idx)
      setActive(updated)
      await loadHand(updated)
      setLastDiscard(updated.currentRound?.discardTop ? null : card)
    } catch (e: any) {
      setErr(e?.message ?? 'Illegal move')
      clearErrSoon()
    }
  }

  const onDraw = async () => {
    if (!active || !user || !isYourTurn) return
    try {
      const before = [...hand]
      const updatedGame = await apiDraw(String(active.id), user)
      setActive(updatedGame)
      const updatedHand = await my_hand(String(active.id), user)

      // Detect new card
      const diff = updatedHand.find(
        (c) => !before.some((b) => b.type === c.type && b.color === c.color && b.value === c.value)
      )
      const drawn = diff ?? updatedHand[updatedHand.length - 1]
      setHand(updatedHand)

      const fresh = await fetchGame(String(active.id))
      if (fresh) setActive(fresh)
      setLastDiscard(null)

      if (drawn) {
        const top = discardTop ?? lastDiscard
        const isPlayable =
          !top ||
          drawn.type === 'WILD' ||
          drawn.type === 'WILD DRAW' ||
          drawn.color === top.color ||
          drawn.type === top.type ||
          drawn.value === top.value
        setDrawnCard(drawn)
        setDrawnIndex(updatedHand.indexOf(drawn))
        setDrawnPlayable(isPlayable)
        setShowDrawModal(true)
      }
    } catch (e: any) {
      setErr(e?.message ?? 'Cannot draw now')
      clearErrSoon()
    }
  }

  const playDrawnCard = async () => {
    if (!active || !user || drawnIndex == null || !drawnCard) return
    if (drawnCard.type === 'WILD' || drawnCard.type === 'WILD DRAW') {
      setPendingWildIndex(drawnIndex)
      setShowColorPicker(true)
      setShowDrawModal(false)
      return
    }
    try {
      const updated = await playCardByIndex(String(active.id), user, drawnIndex)
      setActive(updated)
      await loadHand(updated)
      setLastDiscard(updated.currentRound?.discardTop ? null : drawnCard)
    } catch (e: any) {
      setErr(e?.message ?? 'Illegal move')
      clearErrSoon()
    } finally {
      setShowDrawModal(false)
      setDrawnCard(null)
      setDrawnIndex(null)
      setDrawnPlayable(false)
    }
  }

  const skipDrawnCard = async () => {
    if (!active || !user) return
    try {
      await skipTurn(String(active.id), user)
    } catch (e: any) {
      setErr(e?.message ?? 'Cannot skip now')
      clearErrSoon()
    } finally {
      setShowDrawModal(false)
      setDrawnCard(null)
      setDrawnIndex(null)
      setDrawnPlayable(false)
    }
  }

  if (loading) return <div>Loading game…</div>
  if (error) return <div className="error">{error}</div>
  if (!active) return <div>Game not found.</div>

  return (
    <div className="game">
      <h2>UNO Match #{id}</h2>

      {/* Players */}
      <section className="players">
        <h3>Players</h3>
        <ul>
          {players.map((p) => (
            <li
              key={p.id}
              className={[
                p.id === currentPlayer?.id ? 'current' : '',
                user && p.name === user ? 'you' : '',
              ].join(' ')}
            >
              <span>{p.name}</span>
              <small>
                (cards: {p.handCount} · score: {p.score})
                {p.id === currentPlayer?.id && ' · current turn'}
                {user && p.name === user && ' · you'}
              </small>
            </li>
          ))}
        </ul>
      </section>

      {/* Table */}
      <section className="table">
        <h3>Discard pile</h3>
        <div className="discard">
          {cardToShow ? <Card card={cardToShow} /> : <div className="placeholder">No discard yet</div>}
        </div>
        <p className="meta">
          Draw pile: {round?.drawPileCount ?? 0} · Direction:{' '}
          {round?.direction === -1 ? '⟲ CCW' : '⟳ CW'}
        </p>
      </section>

      {/* Actions */}
      <section className="actions">
        <button onClick={onDraw} disabled={!isYourTurn}>
          Draw
        </button>
        {!isYourTurn && <p className="hint">Wait for your turn to draw.</p>}
        {err && <p className="error">{err}</p>}
      </section>

      {/* Hand */}
      {user && (
        <section className="hand">
          <h3>{user}'s hand (score: {myScore})</h3>
          <div className="cards">
            {hand.map((c, idx) => (
              <Card
                key={idx + '-' + (c.color || 'WILD') + '-' + c.type + '-' + c.value}
                card={c}
                className={!isYourTurn ? 'disabled' : ''}
                onClick={() => onPlay(idx)}
              />
            ))}
          </div>
        </section>
      )}

      {/* Modals */}
      {showColorPicker && (
        <div className="modal-overlay">
          <div className="modal">
            <h4>Pick a color</h4>
            <div className="colors">
              {['RED', 'BLUE', 'GREEN', 'YELLOW'].map((col) => (
                <button key={col} className={`color ${col.toLowerCase()}`} onClick={() => chooseColor(col)}>
                  {col.charAt(0) + col.slice(1).toLowerCase()}
                </button>
              ))}
            </div>
            <div className="modal-actions">
              <button onClick={() => setShowColorPicker(false)}>Cancel</button>
            </div>
          </div>
        </div>
      )}

      {showDrawModal && (
        <div className="modal-overlay">
          <div className="modal">
            <h4>Drawn card</h4>
            {drawnCard && <Card card={drawnCard} />}
            <p>Would you like to play this card or skip your turn?</p>
            <div className="modal-actions">
              <button onClick={playDrawnCard} disabled={!drawnPlayable}>
                Play
              </button>
              <button onClick={skipDrawnCard}>Skip</button>
            </div>
          </div>
        </div>
      )}

      {isFinished && (
        <div className="modal-overlay">
          <div className="modal">
            <h3>Game Over</h3>
            <p>{winnerName ? `${winnerName} reached 500 points and wins!` : 'We have a winner!'}</p>
            <div className="modal-actions">
              <button onClick={() => navigate('/')}>Return to Lobby</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default Game
