// Client/UNO/src/Views/Pending.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { usePendingUnoStore } from '../stores/pending_games_store';
import { usePlayerStore } from '../stores/player_store';

const pendingStore = usePendingUnoStore();
const user = usePlayerStore();
const route = useRoute();
const router = useRouter();
const gameId = String(route.params.id);

const game = computed(() =>
  pendingStore.gameList.find(g => String(g.id) === gameId)
);

onMounted(async () => {
  // Guard: if no player name is set, send user back to lobby to enter a name
  if (!user.player) {
    router.push('/');
    return;
  }

  await pendingStore.loadPendingGames();

  // ✅ Let store handle redirect when game starts
  pendingStore.subscribeToUpdates((id) => {
    if (String(id) === gameId) {
      console.log(`🎉 Game ${id} started — redirecting...`);
      router.push(`/game/${id}`);
    }
  });
});
</script>


<template>
  <div class="pending-page">
    <h2>Pending Game #{{ gameId }}</h2>

    <div v-if="pendingStore.loading">Loading game...</div>

    <div v-else-if="pendingStore.error" class="error">
      Failed to load game.
    </div>

    <div v-else-if="!game">
      Game not found.
    </div>

    <div v-else>
      <p>
        Players joined: {{ game.players?.length ?? 0 }}/{{ game.number_of_players ?? '?' }}
      </p>

      <ul v-if="(game.players?.length ?? 0) > 0">
        <li v-for="player in game.players" :key="player">{{ player }}</li>
      </ul>

      <p v-if="(game.players?.length ?? 0) < (game.number_of_players ?? 0)">
        Waiting for remaining players to join...
      </p>
      <p v-else>All players have joined! Game starting...</p>
    </div>
  </div>
</template>

<style scoped>
.pending-page {
  max-width: 600px;
}
.error {
  color: red;
  margin: 1rem 0;
}
ul {
  list-style-type: disc;
  padding-left: 1.5rem;
  margin-bottom: 1rem;
}
</style>

// Client/UNO/src/pages/Pending.tsx
import React, { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppSelector, useAppDispatch } from '../store/hooks';
import { fetchPendingGames, selectGameById, subscribeToUpdates } from '../store/pendingGamesSlice';
//import ./PendingGame.css';

const PendingGame: React.FC = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const gameId = id ?? '';

  const player = useAppSelector((state) => state.player.player);
  const pendingState = useAppSelector((state) => state.pendingGames);
  const game = useAppSelector((state) => selectGameById(state, gameId));

  useEffect(() => {
    // Guard: if no player name is set, redirect to lobby
    if (!player) {
      navigate('/');
      return;
    }

    // Load all pending games
    dispatch(fetchPendingGames());

    // Subscribe to pending game updates (redirect if game starts)
    const unsub = subscribeToUpdates((startedGameId: string) => {
      if (startedGameId === gameId) {
        console.log(`🎉 Game ${startedGameId} started — redirecting...`);
        navigate(`/game/${startedGameId}`);
      }
    });

    // Cleanup subscription on unmount
    return () => unsub();
  }, [dispatch, gameId, navigate, player]);

  const playersJoined = game?.players?.length ?? 0;
  const totalPlayers = game?.number_of_players ?? 0;

  return (
    <div className="pending-page">
      <h2>Pending Game #{gameId}</h2>

      {pendingState.loading && <div>Loading game...</div>}

      {!pendingState.loading && pendingState.error && (
        <div className="error">Failed to load game.</div>
      )}

      {!pendingState.loading && !pendingState.error && !game && <div>Game not found.</div>}

      {!pendingState.loading && !pendingState.error && game && (
        <>
          <p>
            Players joined: {playersJoined}/{totalPlayers || '?'}
          </p>

          {playersJoined > 0 && (
            <ul>
              {game.players.map((p, idx) => (
                <li key={idx}>{p}</li>
              ))}
            </ul>
          )}

          {playersJoined < totalPlayers ? (
            <p>Waiting for remaining players to join...</p>
          ) : (
            <p>All players have joined! Game starting...</p>
          )}
        </>
      )}
    </div>
  );
};

export default PendingGame;
